# Copyright 2025 OpenSynergy Indonesia
# Copyright 2025 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl-3.0-standalone.html).
{
    "name": "General Audit - Core",
    "version": "14.0.1.0.0",
    "website": "https://simetri-sinergi.id",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "license": "AGPL-3",
    "installable": True,
    "application": False,
    "depends": [
        # Web Theme
        "muk_web_theme",
        "base_user_role",
        # PE
        "ssi_general_audit_worksheet_acceptance_continuance",
        "ssi_general_audit_worksheet_assignment_letter",
        "ssi_general_audit_worksheet_audit_working_plan",
        "ssi_general_audit_worksheet_engagement_letter_checklist",
        "ssi_general_audit_worksheet_independence_statement",
        "ssi_general_audit_worksheet_team_communication",
        # RA
        "ssi_general_audit_worksheet_client_package",
        "ssi_general_audit_worksheet_trial_balance",
        "ssi_general_audit_worksheet_understanding_entity",
        "ssi_general_audit_worksheet_preliminary_materiality",
        "ssi_general_audit_worksheet_preliminary_analytic_procedure",
        "ssi_general_audit_worksheet_planning_memorandum",
        "ssi_general_audit_worksheet_inherent_risk",
        "ssi_general_audit_worksheet_control_risk",
        "ssi_general_audit_worksheet_romm",
        "ssi_general_audit_worksheet_external_communication",
        # RR
        "ssi_general_audit_worksheet_lead_schedule",
        "ssi_general_audit_worksheet_specific_procedure",
        "ssi_general_audit_worksheet_expert",
        # WR
        "ssi_general_audit_worksheet_audit_result",
        "ssi_general_audit_worksheet_final_materiality",
        "ssi_general_audit_worksheet_draft_reporting",
        "ssi_general_audit_worksheet_review",
        "ssi_general_audit_worksheet_final_report",
        # From odoo_module.xlsx
        "web_advanced_search",
        "web_copy_confirm",
        "web_disable_export_group",
        "web_field_required_invisible_manager",
        "web_group_expand",
        "web_ir_actions_act_multi",
        "web_ir_actions_act_view_reload",
        "web_ir_actions_act_window_message",
        "web_listview_range_select",
        "web_m2x_options",
        "web_m2x_options_manager",
        "web_notify",
        "web_notify_channel_message",
        "web_pwa_oca",
        "web_refresher",
        "web_remember_tree_column_width",
        "web_search_with_and",
        "web_send_message_popup",
        "web_tree_dynamic_colored_field",
        "web_tree_many2one_clickable",
        "web_view_calendar_list",
        "web_widget_char_size",
        "web_widget_child_selector",
        "web_widget_image_download",
        "web_widget_image_webcam",
        "web_widget_open_tab",
        "web_widget_text_markdown",
        "web_widget_url_advanced",
        "web_widget_x2many_2d_matrix",
        "auditlog",
        "configuration_helper",
        "database_cleanup",
        "excel_import_export",
        "onchange_helper",
        "sql_export",
        "sql_export_excel",
        "sql_export_mail",
        "sql_request_abstract",
        # "tracking_manager",
        "date_range",
        "mass_editing",
        "mass_operation_abstract",
        "multi_step_wizard",
        "sequence_range_end",
        "sequence_reset_period",
        "server_action_domain",
        "base_user_role",
        "server_action_navigate",
        "auth_admin_passkey",
        "bi_sql_editor",
        "report_async",
        "report_py3o",
        "report_xlsx",
        "report_xlsx_helper",
        "ks_dashboard_ninja",
        # "muk_rest",
        # "muk_webhooks",
        "auth_session_timeout",
        "password_security",
        "filter_multi_user",
        "base_cron_exclusion",
        "base_m2m_custom_field",
        "document_url",
        "mail_attach_existing_attachment",
        "mail_full_expand",
        "mail_optional_autofollow",
        "mail_preview_base",
        "mail_template_multi_attachment",
        "base_copy_user_access",
        "base_custom_system_parameter",
        "base_duration",
        "base_public_holiday",
        "base_user_copy_user_role",
        "ssi_partner",
        "ssi_partner_education_level",
        "ssi_partner_experience",
        "ssi_partner_identification",
        "ssi_hr",
    ],
    "data": [
        "security/res_groups/system_administrator.xml",
        "security/res_groups/audit_team.xml",
        "security/res_groups/ou_administrator.xml",
        "security/res_groups/aura_no_one.xml",
        "security/res_users_role/system_administrator.xml",
        "security/res_users_role/ou_administrator.xml",
        "security/res_users_role/audit_team.xml",
        "data/ir_config_parameter.xml",
        "data/res_currency.xml",
        "data/res_company.xml",
        "data/company_ownership_type.xml",
        "menu.xml",
        "templates/web_login.xml",
        "templates/auth_signup_reset_password.xml",
        "templates/auth_signup_fields.xml",
        "views/res_users.xml",
    ],
}
