# Copyright 2022 OpenSynergy Indonesia
# Copyright 2022 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl-3.0-standalone.html).
# pylint: disable=locally-disabled, manifest-required-author
{
    "name": "General Audit Worksheet - Understanding Entity and It's Environment",
    "version": "14.0.1.15.1",
    "website": "https://simetri-sinergi.id",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "license": "AGPL-3",
    "installable": True,
    "depends": [
        "ssi_general_audit",
        "ssi_general_audit_worksheet_audit_working_plan",
    ],
    "data": [
        "security/ir_module_category_data.xml",
        "security/res_group_data.xml",
        "security/res_group/general_audit_ws_a13a30e.xml",
        "security/res_group/general_audit_ws_c0d0898.xml",
        "security/ir_model_access/general_audit_ws_a13a30e.xml",
        "security/ir_model_access/general_audit_ws_c0d0898.xml",
        "security/ir_rule/general_audit_ws_a13a30e.xml",
        "security/ir_rule/general_audit_ws_c0d0898.xml",
        "data/ir_sequence/general_audit_ws_a13a30e.xml",
        "data/ir_sequence/general_audit_ws_c0d0898.xml",
        "data/sequence_template/general_audit_ws_a13a30e.xml",
        "data/sequence_template/general_audit_ws_c0d0898.xml",
        "data/policy_template/general_audit_ws_a13a30e.xml",
        "data/policy_template/general_audit_ws_c0d0898.xml",
        "data/approval_template/general_audit_ws_a13a30e.xml",
        "data/approval_template/general_audit_ws_c0d0898.xml",
        "data/general_audit_worksheet_type_data.xml",
        # MASTER DATA
        "data/master/general_audit_worksheet_conclusion.xml",
        "data/master/general_audit_going_concern_category.xml",
        "data/master/general_audit_going_concern.xml",
        "data/master/general_audit_fs_preparation_step.xml",
        "data/master/general_audit_fraud_factor_category.xml",
        "data/master/general_audit_fraud_factor.xml",
        "data/master/general_audit_fraud_factor_indicator.xml",
        "data/master/general_audit_class_transaction.xml",
        "data/master/general_audit_expert_type.xml",
        "data/master/ownership_location.xml",
        "data/master/general_audit_business_function.xml",
        "data/master/general_audit_business_document.xml",
        "data/master/general_audit_other_report.xml",
        "menu.xml",
        "views/master/ownership_location_views.xml",
        "views/master/accounting_application_views.xml",
        "views/master/general_audit_class_transaction_views.xml",
        "views/master/general_audit_business_function_views.xml",
        "views/master/general_audit_business_document_views.xml",
        "views/master/general_audit_going_concern_category_views.xml",
        "views/master/general_audit_going_concern_views.xml",
        "views/master/general_audit_fs_preparation_step_views.xml",
        "views/master/general_audit_fraud_factor_category_views.xml",
        "views/master/general_audit_fraud_factor_views.xml",
        "views/master/general_audit_fraud_factor_indicator_views.xml",
        "views/master/general_audit_expert_type_views.xml",
        "views/master/general_audit_fraud_other_report_views.xml",
        "views/general_audit_ws_a13a30e_views.xml",
        "views/general_audit_ws_c0d0898_views.xml",
        "views/general_audit_standard_detail_views.xml",
        "views/general_audit_views.xml",
        # f87b2e1 - Understanding of The Entity and it's Environment
        "security/res_group/general_audit_ws_f87b2e1.xml",
        "security/ir_rule/general_audit_ws_f87b2e1.xml",
        "data/ir_sequence/general_audit_ws_f87b2e1.xml",
        "data/sequence_template/general_audit_ws_f87b2e1.xml",
        "data/policy_template/general_audit_ws_f87b2e1.xml",
        "data/approval_template/general_audit_ws_f87b2e1.xml",
        "views/ga_f87b2e1/general_audit_ws_f87b2e1_views.xml",
        # ddf034c - General Information and Legal Aspect
        "security/res_group/general_audit_ws_ddf034c.xml",
        "security/ir_rule/general_audit_ws_ddf034c.xml",
        "data/ir_sequence/general_audit_ws_ddf034c.xml",
        "data/sequence_template/general_audit_ws_ddf034c.xml",
        "data/policy_template/general_audit_ws_ddf034c.xml",
        "data/approval_template/general_audit_ws_ddf034c.xml",
        "views/ga_ddf034c/general_audit_ws_ddf034c_views.xml",
        # e78a3c6 - Structure Organization and Responsibilities
        "security/res_group/general_audit_ws_e78a3c6.xml",
        "security/ir_model_access/general_audit_ws_e78a3c6.xml",
        "security/ir_rule/general_audit_ws_e78a3c6.xml",
        "data/ir_sequence/general_audit_ws_e78a3c6.xml",
        "data/sequence_template/general_audit_ws_e78a3c6.xml",
        "data/policy_template/general_audit_ws_e78a3c6.xml",
        "data/approval_template/general_audit_ws_e78a3c6.xml",
        "views/ga_e78a3c6/general_audit_ws_e78a3c6_views.xml",
        # ae11f7e - Main Business Activity Process
        "security/res_group/general_audit_ws_ae11f7e.xml",
        "security/ir_model_access/general_audit_ws_ae11f7e.xml",
        "security/ir_rule/general_audit_ws_ae11f7e.xml",
        "data/ir_sequence/general_audit_ws_ae11f7e.xml",
        "data/sequence_template/general_audit_ws_ae11f7e.xml",
        "data/policy_template/general_audit_ws_ae11f7e.xml",
        "data/approval_template/general_audit_ws_ae11f7e.xml",
        "views/ga_ae11f7e/general_audit_ws_ae11f7e_views.xml",
        # bdcdfc5 - Understanding of the business environment
        "security/res_group/general_audit_ws_bdcdfc5.xml",
        "security/ir_model_access/general_audit_ws_bdcdfc5.xml",
        "security/ir_rule/general_audit_ws_bdcdfc5.xml",
        "data/ir_sequence/general_audit_ws_bdcdfc5.xml",
        "data/sequence_template/general_audit_ws_bdcdfc5.xml",
        "data/policy_template/general_audit_ws_bdcdfc5.xml",
        "data/approval_template/general_audit_ws_bdcdfc5.xml",
        "views/ga_bdcdfc5/general_audit_ws_bdcdfc5_views.xml",
        # a604795 - Business Cycles Summary
        "security/res_group/general_audit_ws_a604795.xml",
        "security/ir_model_access/general_audit_ws_a604795.xml",
        "security/ir_rule/general_audit_ws_a604795.xml",
        "data/ir_sequence/general_audit_ws_a604795.xml",
        "data/sequence_template/general_audit_ws_a604795.xml",
        "data/policy_template/general_audit_ws_a604795.xml",
        "data/approval_template/general_audit_ws_a604795.xml",
        "views/ga_a604795/general_audit_ws_a604795_views.xml",
        # c0e0eec - Fraud Factor Analysis
        "security/res_group/general_audit_ws_c0e0eec.xml",
        "security/ir_model_access/general_audit_ws_c0e0eec.xml",
        "security/ir_rule/general_audit_ws_c0e0eec.xml",
        "data/ir_sequence/general_audit_ws_c0e0eec.xml",
        "data/sequence_template/general_audit_ws_c0e0eec.xml",
        "data/policy_template/general_audit_ws_c0e0eec.xml",
        "data/approval_template/general_audit_ws_c0e0eec.xml",
        "views/ga_c0e0eec/general_audit_ws_c0e0eec_views.xml",
        # f6a227 - Understanding of preparation of Financial Statements
        "security/res_group/general_audit_ws_f6a227.xml",
        "security/ir_model_access/general_audit_ws_f6a227.xml",
        "security/ir_rule/general_audit_ws_f6a227.xml",
        "data/ir_sequence/general_audit_ws_f6a227.xml",
        "data/sequence_template/general_audit_ws_f6a227.xml",
        "data/policy_template/general_audit_ws_f6a227.xml",
        "data/approval_template/general_audit_ws_f6a227.xml",
        "views/ga_f6a227/general_audit_ws_f6a227_views.xml",
        "security/ir.model.access.csv",
    ],
    "demo": [],
}
