# Copyright 2025 OpenSynergy Indonesia
# Copyright 2025 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl-3.0-standalone.html).
# pylint: disable=locally-disabled, manifest-required-author
{
    "name": "General Audit Worksheet - Acceptance and Continuance",
    "version": "14.0.1.3.0",
    "website": "https://simetri-sinergi.id",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "license": "AGPL-3",
    "installable": True,
    "depends": [
        "ssi_general_audit",
    ],
    "data": [
        "security/ir_module_category_data.xml",
        "data/general_audit_worksheet_type_data.xml",
        # MASTER DATA
        "data/master/general_audit_worksheet_conclusion.xml",
        "data/master/general_audit_ws_806c4e1_item.xml",
        "data/master/general_audit_ws_369c5a5_item.xml",
        "data/master/general_audit_ws_f5e7049_item.xml",
        "data/master/general_audit_ws_0427d28_item.xml",
        "data/master/general_audit_ws_b9d8a5c_competency_item.xml",
        "data/master/general_audit_ws_b9d8a5c_availability_item.xml",
        "data/master/general_audit_ws_b9d8a5c_independency_item.xml",
        "data/master/general_audit_ws_842f0d6_item_categ.xml",
        "data/master/general_audit_ws_842f0d6_item.xml",
        # 806c4e1 - PE.110 Acceptance and Continuance of
        # Client Relationships Analysis
        "security/res_group/general_audit_ws_806c4e1.xml",
        "security/ir_rule/general_audit_ws_806c4e1.xml",
        "data/ir_sequence/general_audit_ws_806c4e1.xml",
        "data/sequence_template/general_audit_ws_806c4e1.xml",
        "data/policy_template/general_audit_ws_806c4e1.xml",
        "data/approval_template/general_audit_ws_806c4e1.xml",
        "views/ga_806c4e1/general_audit_ws_806c4e1_views.xml",
        "views/ga_806c4e1/general_audit_ws_806c4e1_item_views.xml",
        # 369c5a5 - PE.110.1 Previous Financial Reporting Issues
        "security/res_group/general_audit_ws_369c5a5.xml",
        "security/ir_rule/general_audit_ws_369c5a5.xml",
        "data/ir_sequence/general_audit_ws_369c5a5.xml",
        "data/sequence_template/general_audit_ws_369c5a5.xml",
        "data/policy_template/general_audit_ws_369c5a5.xml",
        "data/approval_template/general_audit_ws_369c5a5.xml",
        "views/ga_369c5a5/general_audit_ws_369c5a5_views.xml",
        "views/ga_369c5a5/general_audit_ws_369c5a5_item_views.xml",
        # f5e7049 - PE.110.2 Management Integrity
        "security/res_group/general_audit_ws_f5e7049.xml",
        "security/ir_rule/general_audit_ws_f5e7049.xml",
        "data/ir_sequence/general_audit_ws_f5e7049.xml",
        "data/sequence_template/general_audit_ws_f5e7049.xml",
        "data/policy_template/general_audit_ws_f5e7049.xml",
        "data/approval_template/general_audit_ws_f5e7049.xml",
        "views/ga_f5e7049/general_audit_ws_f5e7049_views.xml",
        "views/ga_f5e7049/general_audit_ws_f5e7049_item_views.xml",
        # 842f0d6 - PE.110.2.1 Money Laundring Issues
        "security/res_group/general_audit_ws_842f0d6.xml",
        "security/ir_rule/general_audit_ws_842f0d6.xml",
        "data/ir_sequence/general_audit_ws_842f0d6.xml",
        "data/sequence_template/general_audit_ws_842f0d6.xml",
        "data/policy_template/general_audit_ws_842f0d6.xml",
        "data/approval_template/general_audit_ws_842f0d6.xml",
        "views/ga_842f0d6/general_audit_ws_842f0d6_views.xml",
        "views/ga_842f0d6/general_audit_ws_842f0d6_item_categ_views.xml",
        "views/ga_842f0d6/general_audit_ws_842f0d6_item_views.xml",
        # 805d4d5 - PE.110.2.2 Know your customer principles
        "security/res_group/general_audit_ws_805d4d5.xml",
        "security/ir_rule/general_audit_ws_805d4d5.xml",
        "data/ir_sequence/general_audit_ws_805d4d5.xml",
        "data/sequence_template/general_audit_ws_805d4d5.xml",
        "data/policy_template/general_audit_ws_805d4d5.xml",
        "data/approval_template/general_audit_ws_805d4d5.xml",
        "views/ga_805d4d5/general_audit_ws_805d4d5_views.xml",
        # b9d8a5c - PE.110.3 Competency, availability, and
        # independency of assignment team
        "security/res_group/general_audit_ws_b9d8a5c.xml",
        "security/ir_rule/general_audit_ws_b9d8a5c.xml",
        "data/ir_sequence/general_audit_ws_b9d8a5c.xml",
        "data/sequence_template/general_audit_ws_b9d8a5c.xml",
        "data/policy_template/general_audit_ws_b9d8a5c.xml",
        "data/approval_template/general_audit_ws_b9d8a5c.xml",
        "views/ga_b9d8a5c/general_audit_ws_b9d8a5c_views.xml",
        "views/ga_b9d8a5c/general_audit_ws_b9d8a5c_competency_item_views.xml",
        "views/ga_b9d8a5c/general_audit_ws_b9d8a5c_availability_item_views.xml",
        "views/ga_b9d8a5c/general_audit_ws_b9d8a5c_independency_item_views.xml",
        # 0427d28 - PE.110.4 Communication with previous auditor
        "security/res_group/general_audit_ws_0427d28.xml",
        "security/ir_rule/general_audit_ws_0427d28.xml",
        "data/ir_sequence/general_audit_ws_0427d28.xml",
        "data/sequence_template/general_audit_ws_0427d28.xml",
        "data/policy_template/general_audit_ws_0427d28.xml",
        "data/approval_template/general_audit_ws_0427d28.xml",
        "views/ga_0427d28/general_audit_ws_0427d28_views.xml",
        "views/ga_0427d28/general_audit_ws_0427d28_item_views.xml",
        "security/ir.model.access.csv",
    ],
    "demo": [],
}
