# Copyright 2022 OpenSynergy Indonesia
# Copyright 2022 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl-3.0-standalone.html).
# pylint: disable=locally-disabled, manifest-required-author
{
    "name": "General Audit Worksheet - Control Risk",
    "version": "14.0.2.7.0",
    "website": "https://simetri-sinergi.id",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "license": "AGPL-3",
    "installable": True,
    "depends": [
        "ssi_general_audit_worksheet_understanding_entity",
        "ssi_general_audit_worksheet_inherent_risk",
    ],
    "data": [
        "security/res_group_data.xml",
        "security/ir_module_category_data.xml",
        "data/general_audit_worksheet_type_data.xml",
        # MASTER DATA
        "data/master/general_audit_worksheet_conclusion.xml",
        "data/master/general_audit_assersion_type.xml",
        "data/master/general_audit_control_activity.xml",
        "data/master/general_audit_key_internal_control.xml",
        "data/master/general_audit_general_control_category.xml",
        "data/master/general_audit_general_control.xml",
        "data/master/general_audit_general_control_indicator.xml",
        "data/master/general_audit_general_control_set.xml",
        "data/master/general_audit_it_control_category.xml",
        "data/master/general_audit_it_control.xml",
        "data/master/general_audit_it_control_indicator.xml",
        "data/master/general_audit_it_control_set.xml",
        "data/master/general_audit_account_key_internal_control.xml",
        "menu.xml",
        # MASTER
        "views/master/general_audit_assersion_type_views.xml",
        "views/master/general_audit_control_activity_views.xml",
        "views/master/general_audit_key_internal_control_views.xml",
        "views/master/general_audit_account_key_internal_control_views.xml",
        "views/master/general_audit_general_control_category_views.xml",
        "views/master/general_audit_general_control_views.xml",
        "views/master/general_audit_general_control_indicator_views.xml",
        "views/master/general_audit_general_control_set_views.xml",
        "views/master/general_audit_it_control_category_views.xml",
        "views/master/general_audit_it_control_views.xml",
        "views/master/general_audit_it_control_indicator_views.xml",
        "views/master/general_audit_it_control_set_views.xml",
        # a58e29c - Control Risk
        "security/res_group/general_audit_ws_a58e29c.xml",
        "security/ir_rule/general_audit_ws_a58e29c.xml",
        "data/ir_sequence/general_audit_ws_a58e29c.xml",
        "data/sequence_template/general_audit_ws_a58e29c.xml",
        "data/policy_template/general_audit_ws_a58e29c.xml",
        "data/approval_template/general_audit_ws_a58e29c.xml",
        "views/ga_a58e29c/general_audit_ws_a58e29c_views.xml",
        # b59b886 - Control Risk - Entity Level
        "security/res_group/general_audit_ws_b59b886.xml",
        "security/ir_rule/general_audit_ws_b59b886.xml",
        "data/ir_sequence/general_audit_ws_b59b886.xml",
        "data/sequence_template/general_audit_ws_b59b886.xml",
        "data/policy_template/general_audit_ws_b59b886.xml",
        "data/approval_template/general_audit_ws_b59b886.xml",
        "views/ga_b59b886/general_audit_ws_b59b886_views.xml",
        # d3d2719 - General Control Evaluations
        "security/res_group/general_audit_ws_d3d2719.xml",
        "security/ir_model_access/general_audit_ws_d3d2719.xml",
        "security/ir_rule/general_audit_ws_d3d2719.xml",
        "data/ir_sequence/general_audit_ws_d3d2719.xml",
        "data/sequence_template/general_audit_ws_d3d2719.xml",
        "data/policy_template/general_audit_ws_d3d2719.xml",
        "data/approval_template/general_audit_ws_d3d2719.xml",
        "views/ga_d3d2719/general_audit_ws_d3d2719_views.xml",
        # f63f569 - IT Control Evaluations
        "security/res_group/general_audit_ws_f63f569.xml",
        "security/ir_model_access/general_audit_ws_f63f569.xml",
        "security/ir_rule/general_audit_ws_f63f569.xml",
        "data/ir_sequence/general_audit_ws_f63f569.xml",
        "data/sequence_template/general_audit_ws_f63f569.xml",
        "data/policy_template/general_audit_ws_f63f569.xml",
        "data/approval_template/general_audit_ws_f63f569.xml",
        "views/ga_f63f569/general_audit_ws_f63f569_views.xml",
        # eabdaad - Control Risk - Cycle Level
        "security/res_group/general_audit_ws_eabdaad.xml",
        "security/ir_model_access/general_audit_ws_eabdaad.xml",
        "security/ir_rule/general_audit_ws_eabdaad.xml",
        "data/ir_sequence/general_audit_ws_eabdaad.xml",
        "data/sequence_template/general_audit_ws_eabdaad.xml",
        "data/policy_template/general_audit_ws_eabdaad.xml",
        "data/approval_template/general_audit_ws_eabdaad.xml",
        "views/ga_eabdaad/general_audit_ws_eabdaad_views.xml",
        # ba9b2f0 - Significant Account
        "security/res_group/general_audit_ws_ba9b2f0.xml",
        "security/ir_model_access/general_audit_ws_ba9b2f0.xml",
        "security/ir_rule/general_audit_ws_ba9b2f0.xml",
        "data/ir_sequence/general_audit_ws_ba9b2f0.xml",
        "data/sequence_template/general_audit_ws_ba9b2f0.xml",
        "data/policy_template/general_audit_ws_ba9b2f0.xml",
        "data/approval_template/general_audit_ws_ba9b2f0.xml",
        "views/ga_ba9b2f0/general_audit_ws_ba9b2f0_views.xml",
        "security/ir.model.access.csv",
    ],
    "demo": [],
}
