# Copyright 2022 OpenSynergy Indonesia
# Copyright 2022 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl-3.0-standalone.html).
{
    "name": "General Audit",
    "version": "14.0.3.3.0",
    "category": "Administration",
    "website": "https://simetri-sinergi.id",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "license": "AGPL-3",
    "installable": True,
    "application": True,
    "depends": [
        "ssi_hr",
        "ssi_partner",
        "ssi_accountant_report",
        "ssi_master_data_mixin",
        "ssi_transaction_partner_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_open_mixin",
        "ssi_decorator",
    ],
    "data": [
        "security/ir_module_category_data.xml",
        "security/res_group_data.xml",
        "security/ir.model.access.csv",
        "security/ir_rule_data.xml",
        "data/ir_sequence_data.xml",
        "data/sequence_template_data.xml",
        "data/policy_template_data.xml",
        "data/approval_template_data.xml",
        "data/general_audit_worksheet_type_category_data.xml",
        # MASTER DATA
        "data/master/client_financial_ratio.xml",
        "data/master/general_audit_business_environment.xml",
        "data/master/client_business_process.xml",
        "data/master/client_account_group.xml",
        "data/master/trial_balance_computation_item.xml",
        "data/master/client_account_type.xml",
        "data/master/team_role.xml",
        "data/master/checklist_option.xml",
        "data/master/checklist_option_set.xml",
        "menu.xml",
        "wizards/import_client_account.xml",
        "wizards/import_trial_balance_detail.xml",
        "views/employee/hr_employee_views.xml",
        "views/team_role/team_role_views.xml",
        "views/checklist/checklist_option_set_views.xml",
        "views/checklist/checklist_option_views.xml",
        "views/client_account/client_account_group_views.xml",
        "views/client_account/client_account_type_views.xml",
        "views/client_account/client_account_views.xml",
        "views/client_account/client_account_type_set_views.xml",
        "views/tb/trial_balance_computation_item_views.xml",
        "views/client_financial_ratio_views.xml",
        "views/client_business_process_views.xml",
        "views/ga/general_audit_relevant_regulation_views.xml",
        "views/ga/general_audit_business_environment_views.xml",
        "views/worksheet/general_audit_worksheet_type_category_views.xml",
        "views/worksheet/general_audit_worksheet_type_views.xml",
        "views/worksheet/general_audit_worksheet_conclusion_views.xml",
        "views/ga/general_audit_views.xml",
        "views/ga/general_audit_computation_views.xml",
        "views/ga/general_audit_detail_views.xml",
        "views/ga/general_audit_group_detail_views.xml",
        "views/ga/general_audit_standard_detail_views.xml",
        "views/ga/general_audit_standard_audit_views.xml",
        "views/tb/client_trial_balance_views.xml",
        "views/tb/client_trial_balance_detail_views.xml",
        "views/tb/client_trial_balance_computation_views.xml",
        "views/tb/client_trial_balance_group_detail_views.xml",
        "views/tb/client_trial_balance_standard_detail_views.xml",
        "views/client_adjustment_entry_views.xml",
        "views/client_account/client_account_mapping_views.xml",
        "views/worksheet/general_audit_worksheet_mixin_views.xml",
        "templates/checklist_templates.xml",
    ],
    "demo": [
        # "demo/client_account_type_set_demo.xml",
    ],
}
