import setuptools

with open('VERSION.txt', 'r') as f:
    version = f.read().strip()

setuptools.setup(
    name="odoo14-addons-open-synergy-ssi-general-audit",
    description="Meta package for open-synergy-ssi-general-audit Odoo addons",
    version=version,
    install_requires=[
        'odoo14-addon-ssi_general_audit',
        'odoo14-addon-ssi_general_audit_core',
        'odoo14-addon-ssi_general_audit_worksheet_acceptance_continuance',
        'odoo14-addon-ssi_general_audit_worksheet_analytic_cycle',
        'odoo14-addon-ssi_general_audit_worksheet_assignment_letter',
        'odoo14-addon-ssi_general_audit_worksheet_audit_procedure_analytic',
        'odoo14-addon-ssi_general_audit_worksheet_audit_procedure_confirmation',
        'odoo14-addon-ssi_general_audit_worksheet_audit_procedure_inquiry',
        'odoo14-addon-ssi_general_audit_worksheet_audit_procedure_observation',
        'odoo14-addon-ssi_general_audit_worksheet_audit_procedure_recompute',
        'odoo14-addon-ssi_general_audit_worksheet_audit_procedure_reperformance',
        'odoo14-addon-ssi_general_audit_worksheet_audit_procedure_vouching',
        'odoo14-addon-ssi_general_audit_worksheet_audit_result',
        'odoo14-addon-ssi_general_audit_worksheet_audit_working_plan',
        'odoo14-addon-ssi_general_audit_worksheet_client_package',
        'odoo14-addon-ssi_general_audit_worksheet_control_risk',
        'odoo14-addon-ssi_general_audit_worksheet_draft_reporting',
        'odoo14-addon-ssi_general_audit_worksheet_engagement_letter_checklist',
        'odoo14-addon-ssi_general_audit_worksheet_expert',
        'odoo14-addon-ssi_general_audit_worksheet_external_communication',
        'odoo14-addon-ssi_general_audit_worksheet_final_materiality',
        'odoo14-addon-ssi_general_audit_worksheet_final_report',
        'odoo14-addon-ssi_general_audit_worksheet_independence_statement',
        'odoo14-addon-ssi_general_audit_worksheet_inherent_risk',
        'odoo14-addon-ssi_general_audit_worksheet_lead_schedule',
        'odoo14-addon-ssi_general_audit_worksheet_physical_check',
        'odoo14-addon-ssi_general_audit_worksheet_planning_memorandum',
        'odoo14-addon-ssi_general_audit_worksheet_population',
        'odoo14-addon-ssi_general_audit_worksheet_preliminary_analytic_procedure',
        'odoo14-addon-ssi_general_audit_worksheet_preliminary_materiality',
        'odoo14-addon-ssi_general_audit_worksheet_review',
        'odoo14-addon-ssi_general_audit_worksheet_romm',
        'odoo14-addon-ssi_general_audit_worksheet_sample_determination',
        'odoo14-addon-ssi_general_audit_worksheet_specific_procedure',
        'odoo14-addon-ssi_general_audit_worksheet_team_communication',
        'odoo14-addon-ssi_general_audit_worksheet_test_of_control',
        'odoo14-addon-ssi_general_audit_worksheet_test_of_detail',
        'odoo14-addon-ssi_general_audit_worksheet_test_planning',
        'odoo14-addon-ssi_general_audit_worksheet_trial_balance',
        'odoo14-addon-ssi_general_audit_worksheet_understanding_entity',
    ],
    classifiers=[
        'Programming Language :: Python',
        'Framework :: Odoo',
        'Framework :: Odoo :: 14.0',
    ]
)
